### ISSUE TITLE
Got error on project startup

### ISSUE THREAD

**Issue by royigoldi** [devyumao/angular2-busy#1]
Hi,
I installed the pacakge and add it also to systemjs.config:
var map = {
        'app':                        'app', // 'dist',
        '@angular':                   'node_modules/@angular',
        'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
        'rxjs':                       'node_modules/rxjs',
         'jquery': 'node_modules/jquery/dist/jquery.js',
        'bootstrap': 'node_modules/bootstrap/dist/js/bootstrap.js',
        'jquery-ui': 'node_modules/jquery-ui/jquery-ui.js',
        'daterangepicker': 'node_modules/daterangepicker/daterangepicker.js',
        'moment': 'node_modules/moment/moment.js',
        'primeng': 'node_modules/primeng',
        'angular2-busy': 'node_modules/angular2-busy'
var packages = {
        'app':      { main: 'main.js',  defaultExtension: 'js' },
        'rxjs':      { defaultExtension: 'js' },
        'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' },
        'primeng': { defaultExtension: 'js' },
        'moment': { defaultExtension: 'js' },
        'angular2-busy': { main: 'index.js', defaultExtension: 'js' },

 and got this error:

localhost/:41 Error: Error: XHR error (404 Not Found) loading http://localhost:3000/node_modules/angular2-busy/build/src.js(…)

I will thank you for your help...

**Comment by devyumao** [comment]
Hi royigoldi,
v0.2.7 fixes this bug on SystemJS-based project.
Thank for your issue.
