### ISSUE TITLE
Error on fetch:  node_modules/angular2-dynamic-component/index

### ISSUE THREAD

**Issue by damoncasale** [devyumao/angular2-busy#10]
Error on fetch:  node_modules/angular2-dynamic-component/index

I get this compile error when attempting to use angular2-busy.  I checked and noticed that angular2-dynamic-component isn't even a dependency.

**Comment by devyumao** [comment]
Maybe your npm version did not install the secondary dependencies in a flat way, and you may install them manually:

``` shell
npm install --save ts-metadata-helper@0.0.3
npm install --save angular2-dynamic-component@0.0.50
```

**Comment by damoncasale** [comment]
After those two dependencies, there was another dependency on core-js/es7/Reflect, and I gave up and reverted to 1.0.1 which works fine.

**Comment by devyumao** [comment]
Sorry for the missing of the `system.config.js` introduction. The README has been updated.

**Comment by corner22** [comment]
I had a similar problem with 1.0.2 and resolved by adding the missing info from system.config.js.  like damoncasale, I then also got 404 errors with core-js (mine was actually core-js/es6/reflect).  I installed 1.0.1 and it now works fine for me too.

**Comment by bravenewworlds** [comment]
I've got the same behaviour
ts-metadata-helper and angular2-dynamic-component are resolved, but "reflect" is not:

![error](https://cloud.githubusercontent.com/assets/17614786/19645694/b5d8942a-99fe-11e6-9478-911879431c12.png)

UPD: I made it (v. 1.0.2) work when added this to systemjs.config.js

```
map: { 
...
'core-js': 'npm:core-js' ,
}
...
packages: {
...
'core-js': { defaultExtension: 'js' },
}
```

**Comment by devyumao** [comment]
Now the module does not rely on angular2-dynamic-component any more.
