### ISSUE TITLE
support for webpack

### ISSUE THREAD

**Issue by fmongarex** [devyumao/angular2-busy#14]
do you have any support for webpack?

**Comment by al-pt-old** [comment]
What type of support are you expect?

**Comment by Xepe** [comment]
Hello !, 

I am getting the following error, I am not sure if it is related. 

![image](https://cloud.githubusercontent.com/assets/2806076/21371578/cdb267d2-c6d7-11e6-8b3e-5a03071b9d56.png)

Thanks. 
Regards.

**Comment by figuerres** [comment]
i just started a fork from this and will see if i can update it to work with angular cli see here: https://github.com/figuerres/ng-busy
give me a few days and then see if you want to add to this.
