### ISSUE TITLE
ngc compile fail

### ISSUE THREAD

**Issue by alanhe421** [devyumao/angular2-busy#18]
when i run ngc -p ./tsconfig.aot.json
error!
below:
`Error: Error File '/Users/heqiang/WebstormProjects/Bmodule/node_modules/angular2-busy/index.ts' is not under 'rootDir' '/Users/heqiang/WebstormProjects/Bmodule/client'. 'rootDir' is expected to contain all source files.`

`
"@angular/common": "2.1.2",
    "@angular/compiler": "2.1.2",
    "@angular/compiler-cli": "2.1.2",
    "@angular/core": "2.1.2",
    "@angular/forms": "2.1.2",
    "@angular/http": "2.1.2",
    "@angular/platform-browser": "2.1.2",
    "@angular/platform-browser-dynamic": "2.1.2",
    "@angular/platform-server": "2.1.2",
    "@angular/router": "3.1.2",
    "@ng-bootstrap/ng-bootstrap": "1.0.0-alpha.10",
    "angular2-busy": "^1.0.2",

`

**Comment by KarlPurk** [comment]
I was about to open an issue called "Add AoT Compilation Support".   I have a different error, but I believe that this is the same issue.  My error was "Error: Unexpected value 'BusyModule' declared by the module 'AppModule'".

For problem, `ng2-redux` had a similar issue.  I think they solved it by emitting metadata during tsc compilation.  See below:
- https://github.com/angular-redux/ng2-redux/issues/223

The work seems to have been completed in this commit (scroll down to the tsconfig.json diff):
- https://github.com/angular-redux/ng2-redux/commit/130f93b183b36351066c9afb81b741a835b82e65

**Comment by arangelp** [comment]
I am having the same AOT problem:
"Error: Unexpected value 'BusyModule' declared by the module 'AppModule'"

**Comment by KarlPurk** [comment]
Stumbled across this today and thought it might be useful here:
https://github.com/jkuri/ng2-uploader/commit/767a49f437416df2c7faa6e4bf13b059de9b7b94

**Comment by barrytam20** [comment]
a bit hackish, but i resolved this by deleting the index.ts file under node_modules

**Comment by chamodck** [comment]
yes that is working,
thank you @barrytam20
