### ISSUE TITLE
This version is not working in Internet Explorer

### ISSUE THREAD

**Issue by gertadriaensen** [devyumao/angular2-busy#2]
The demo is not working within Internet Explorer. Any ideas?
In Chrome this is working correctly.

**Comment by devyumao** [comment]
Hi gertadriaensen,
v0.2.8 fixes this bug in IE.
Thank for your issue.

**Comment by lichunbin814** [comment]
not working on IE 11  , do you have any ideas?

http://devyumao.github.io/angular2-busy/demo/asset/
