### ISSUE TITLE
No show spinner and message

### ISSUE THREAD

**Issue by ws-gianni** [devyumao/angular2-busy#26]
my code......

**component.html**
<div class="content" style="position: relative" [ngBusy]="busy_config"></div>

**component.ts**
this.busy = this.service.login(this.username, this.password)
                                    .delay(5000)
                                    .finally(() => this.OnComplete())
                                    .subscribe(
                                        resp => this.ResultOnLogin(resp),
                                        error => this.LogError('Login ...', error));
this.busy_config = {'busy': this.busy, 'message': 'Attendere prego...', 'backdrop': true, delay: 200, minDuration': 2000};

backdor works,  spinner and message does not showing.

Thanks for your help

**Comment by martintsan** [comment]
Same issue

**Comment by SteveDrakey** [comment]
I guess you're on bootstrap, the message is behind the navbar.

change the CSS as follows :

```
.ng-busy {
  z-index: 9999;
}
```

**Comment by ws-gianni** [comment]
Great!!   Now works.

Regards

**Comment by loganathansp** [comment]
Super...
