### ISSUE TITLE
Angular2-dynamic-component requires a peer

### ISSUE THREAD

**Issue by chaiwa-berian** [devyumao/angular2-busy#29]
This package is failing to work for me with the following warning, and ultimately fails to import BusyModule. Any help??? Please Log warnings I am getting during installing:
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
})
npm WARN angular2-dynamic-component@0.0.50 requires a peer of @angular/core@~2.0
.0 but none was installed.
npm WARN angular2-dynamic-component@0.0.50 requires a peer of @angular/common@~2
.0.0 but none was installed.
npm WARN angular2-dynamic-component@0.0.50 requires a peer of @angular/compiler@
~2.0.0 but none was installed.
npm WARN angular2-dynamic-component@0.0.50 requires a peer of @angular/platform-
browser@~2.0.0 but none was installed.
npm WARN angular2-dynamic-component@0.0.50 requires a peer of @angular/http@~2.0
.0 but none was installed.
npm WARN angular2-dynamic-component@0.0.50 requires a peer of zone.js@~0.6.13 bu
t none was installed.
npm info ok
```

**Comment by conner-fallone** [comment]
I am also getting this issue... Seems to be that angular2-dymanic-component is using a version of angular less than what we are using. Is there any workaround for this?

**Comment by conner-fallone** [comment]
It looks like angular2-dynamic-component updated their versions to the latest for angular just now, I think we just need the package.json for this library to be updated to the latest version of angular2-dynamic-component which is: "angular2-dynamic-component": "1.3.11"

**Comment by figuerres** [comment]
i just started a fork from this and will see if i can update it to work with angular cli see here: https://github.com/figuerres/ng-busy
give me a few days and then see if you want to add to this.

**Comment by a-zen** [comment]
As @fallXone mentioned an update for angular2-dynamic-component should be enough.
Current version would be 1.3.15.
Can we please release a new version auf angular2-busy with the modified dependency?

**Comment by devyumao** [comment]
Now the module does not rely on angular2-dynamic-component any more.
