### ISSUE TITLE
src folder not added to npm repo

### ISSUE THREAD

**Issue by dispeakble** [devyumao/angular2-busy#3]
index.ts:
export \* from './src';

angular2-busy:
node_modules
index.ts
package.json
README.md

src:
MISSING

**Comment by Juliete** [comment]
I have the same issue.

**Comment by devyumao** [comment]
You may try to reinsall it.

**Comment by Juliete** [comment]
Same result after reinstall, the src folder is missing.

This is the output of the npm install.

c:\wsn-front2>npm install --save angular2-busy
(node:11024) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
npm WARN install Couldn't install optional dependency: Unsupported
wsn-front2@0.0.0 c:\wsn-front2
└─┬ angular2-busy@0.2.1
  ├── @angular/router-deprecated@2.0.0-rc.2
  ├─┬ bootstrap@4.0.0-alpha.4
  │ ├── jquery@3.1.0
  │ └── tether@1.3.7
  └── rxjs@5.0.0-beta.6

**Comment by devyumao** [comment]
You may specify the version. For example:

``` shell
npm install --save angular2-busy@0.3.2-rc.6
```

**Comment by Juliete** [comment]
This way works. Thank you.

**Comment by dispeakble** [comment]
lol
