### ISSUE TITLE
ERROR in BusyModule is not an NgModule

### ISSUE THREAD

**Issue by calvingferrando18** [devyumao/angular2-busy#33]
I get this error when I import BusyModule. Or this library only works on Angular 2.0.0?

  "dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "angular2-busy": "^1.0.2",
    "angularfire2": "^2.0.0-beta.7",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "firebase": "^3.6.8",
    "ng2-bootstrap": "^1.3.2",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^2.3.1",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.26",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.3.0",
    "typescript": "~2.0.3"
  }

**Comment by kthomas80** [comment]
same issue

**Comment by danilodevhub** [comment]
same issue

**Comment by qcnguyen** [comment]
same issue

**Comment by oslanier** [comment]
I have the same problem.

**Comment by flexkiran** [comment]
same issue

**Comment by Trenrod** [comment]
Same

**Comment by SimoneMSR** [comment]
same, tested with
"typescript": "~2.0.3"

**Comment by marciomsm** [comment]
Has anyone fixed this bug?

**Comment by gepisolo** [comment]
Same error for me with:
"@angular/compiler-cli": "^2.3.1",
"angular-cli": "1.0.0-beta.24",
"typescript": "~2.0.3"

**Comment by bashoogzaad** [comment]
same

**Comment by bashoogzaad** [comment]
Any idea how to fix this?

**Comment by michalzfania** [comment]
same issue!!

**Comment by michalzfania** [comment]
same issue. any idea how to fix?

**Comment by emidel** [comment]
same! any idea?

**Comment by ghost** [comment]
the same issue.  any idea when it will be fixed?

**Comment by trueflywood** [comment]
Same error for me with:
"@angular/compiler-cli": "^2.4.8",
"angular-cli": "1.0.0-beta.32.3",

**Comment by nolafs** [comment]
Same issues
"@angular/compiler-cli": "^2.3.1",
"angular-cli": "1.0.0-beta.28.3",

**Comment by tmwnni** [comment]
Same issue here after upgrading to @angular/cli@latest on Windows 10- is there a fix in the works?

@angular/cli: 1.0.0-beta.32.3
node: 7.3.0
os: win32 x64
@angular/cli: 1.0.0-beta.32.3
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/compiler-cli: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8

**Comment by SerhiiTsybulskyi** [comment]
+1

**Comment by justicewebtech** [comment]
A possible workaround, until it is patched, is to comment out
imports: [ ...
    //,BusyModule
...]

Then ng build -w or whatever you prefer.  Once it is built remove the comments.  It just throws a fit during the build but it still works fine.

**Comment by s-inshiy** [comment]
same issue

**Comment by tim-pankoke** [comment]
+1

**Comment by stanciupaul** [comment]
same issue

**Comment by GuiFSimoes** [comment]
yep! same issue...

**Comment by rshatf** [comment]
same here

**Comment by chintharr** [comment]
Same here

**Comment by smainz** [comment]
Changing the order in app.module.ts from

```
@NgModule({
  imports: [
    ...
    BusyModule,

  ],
  declarations: [
   ...

  ],

  ...
}
```

to

```
@NgModule({
  declarations: [
   ...

  ],
  imports: [
    ...
    BusyModule,

  ],
  ...
}
```

worked for me

**Comment by superKalo** [comment]
same here :(

**Comment by superKalo** [comment]
@devyumao , you can take a look at this issue: https://github.com/angular/angular-cli/issues/3426#issuecomment-269673735 maybe it will be able to help.

Do you plan to keep the library updated or it is abandoned currently?

**Comment by dinusuresh** [comment]
I have added the metadata.json files. It works. Please use this until the official module is fixed.

https://github.com/dinusuresh/angular2-busy

_package.json:_
`"angular2-busy": "https://github.com/dinusuresh/angular2-busy.git"`

**NOTE**
I have updated packages in package.json to use latest stable version as per my project needs. If you need them to match yours consider forking and change versions to meet your project needs.

**Comment by superKalo** [comment]
Thank you @dinusuresh ! The solution you provided works on my side too! 👍 

Why don't you consider to issue a pull request to https://github.com/devyumao/angular2-busy ? I bet this would help @devyumao deal with this issue faster.

**Comment by rshatf** [comment]
Yay!  Works great!  Thanks, Dinesh!

**Comment by bgaillard** [comment]
Thanks a lot @dinusuresh 👍  your fix also worked for me.

**Comment by GuiFSimoes** [comment]
Thanks  @dinusuresh  its works for me too!!!

I updated "ts-metadata-helper" and "angular2-dynamic-component" packages in my projetc too...

**Comment by dinusuresh** [comment]
Glad I could help 😄

@superKalo I have created a pull request but considering the author is not active ATM I do not know if and when it will be accepted.

**Comment by M4NC1O** [comment]
Can anyone please explain me how to solve this problem? I didn't understand what I have to change :)

**Comment by dinusuresh** [comment]
@M4NC1O Sure. If you are looking to just get it working, then

In you package.json file make sure the angular2-busy dependency line is like this:
`"angular2-busy": "https://github.com/dinusuresh/angular2-busy.git"`

remove node_modules folder if you have it
```
npm cache clean
npm install
```

**Comment by M4NC1O** [comment]
It works!
thank you!

**Comment by arianul** [comment]
Thank you !

**Comment by Niraj-Sharma** [comment]
It works well..thanks

**Comment by M4NC1O** [comment]
When I build --aot I lose the spinner and the label "Loading..".. does anyone have the same issue?

**Comment by Niraj-Sharma** [comment]
@dinusuresh: started getting error "DynamicComponentModule is not an NgModule"..

**Comment by dinusuresh** [comment]
@Niraj-Sharma Please can you post your package.json and output of `npm install`?

It is working good on my end, the only warning is the rxjs version 5.0.2 which is used by [angular2-dynamic-component](https://github.com/apoterenko/angular2-dynamic-component)

@M4NC1O I will look into it and let you know.

**Comment by dinusuresh** [comment]
@Niraj-Sharma https://github.com/devyumao/angular2-busy/issues/39

**Comment by devyumao** [comment]
Now the module has been fixed.
Thanks, @dinusuresh ! Your solution is great. 👍 
Also thank @superKalo . The issue you mentioned is very helpful.
Sorry for the late reply. The library will be kept updated :)

**Comment by devyumao** [comment]
@Niraj-Sharma Now the module does not rely on angular2-dynamic-component any more. Please update to the latest version.

**Comment by dinusuresh** [comment]
@devyumao Thank you! Glad to have you back :smile:

**Comment by PatilPritam** [comment]
Hello, 

I followed solution by dinusuresh, but it's not working. Please provide solution.
& also wanted to ask that It will create separate instance for different component if we add in diff component.

Currently, I am using loader with observables but problem is loader gets activated for any request to Server it's just because of service we are using. 


Please provide solution.

**Comment by PatilPritam** [comment]
@dinusuresh
