### ISSUE TITLE
Angular2-busy causing issues creating a new src folder and node_modules folder inside build folder

### ISSUE THREAD

**Issue by vijender1256** [devyumao/angular2-busy#34]
I am using angular - > 2.3.0 version, I downloaded angular2-busy and then imported it to app module and then used it in my html file, component.

After I save the component file its creating a new folder inside my build directory with src folder and all my changes are going inside that folder not into my build directory that I refereed in my tsconfig.json file:

my tsconfig.json file:

```
{
  "compilerOptions": {
    "outDir": "build/dist/app",
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "noEmitHelpers": true
  },
  "compileOnSave": true,
  "exclude": [
    "node_modules",
    "build"
  ]
}
```
Above tsconfig.json upon saving of typescript file its used to do tfs checkout and then write the changes into the build/dist/app folder, but after i downloaded angular2-busy everything is breaking all my changes are going inside my build/dist but its creating src folder structure again inside build/dist.

Angular2-busy is completely breaking my working application. any help is appreciated.

**Comment by vijender1256** [comment]
@devyumao is there any issue you are seeing with new versions of angular 2, will there be any fix in near future. I am not seeing any activity going on with angular2-busy in couple of months. Thanks

**Comment by dmarginian** [comment]
This is really a TypeScript issue.  See https://github.com/ceolter/ag-grid-angular/issues/108 for more information.

**Comment by devyumao** [comment]
Hi, @vijender1256 
You may try to update to the latest version.
