### ISSUE TITLE
Don't rely on angular2-dynamic-component

### ISSUE THREAD

**Issue by a-zen** [devyumao/angular2-busy#39]
The module angular2-dynamic-component is no longer necessary as angular supports this feature
now directly with [NgComponentOutlet](https://github.com/angular/angular/issues/9599).

angular2-busy should use the angular feature directly instead of a additional module

**Comment by al-pt-old** [comment]
A good idea.
Since 4.0.x
The module completed its task and is not maintained anymore.

*ngComponentOutlet=
  ngComponentOutletNgModuleFactory <=> componentModules
  content <=> componentTemplate

**Comment by devyumao** [comment]
Thank you, @a-zen and @apoterenko . Your suggestions are great!
Now the module does not rely on angular2-dynamic-component any more. Please update to the latest version.

**Comment by al-pt-old** [comment]
https://github.com/devyumao/angular2-busy/pull/47
