### ISSUE TITLE
Not working in RC5

### ISSUE THREAD

**Issue by Xamlware** [devyumao/angular2-busy#4]
I set it up in the shared module first, no work, then declared it in the component, still no work.  I love this idea, please upgrade to RC5.  Thanks...

![capture](https://cloud.githubusercontent.com/assets/18727766/18034223/5135787e-6d05-11e6-9588-7be8a5dcc435.PNG)

**Comment by SDohle** [comment]
Also not working in rc 6.

**Comment by vanroda** [comment]
rc6 error =>
ERROR in [default] /node_modules/angular2-busy/build/src/busy.directive.d.ts:1:30 
Module '"/node_modules/@angular/core/index"' has no exported member 'DynamicComponentLoader'.

**Comment by devyumao** [comment]
Voila! RC6 is supported.
Thanks for your using.
@Xamlware @SDohle @vanroda
