### ISSUE TITLE
Error in angular 4.0 version

### ISSUE THREAD

**Issue by mgafur** [devyumao/angular2-busy#45]
ERROR Error: Uncaught (in promise): Error: Found the synthetic property @fadeInOut.
Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.

how to fix it

**Comment by jnwanya** [comment]
To fix this:
Step 1 : npm install @angular/animations --save
Step 2: import {BrowserAnimationsModule} from '@angular/platform-browser/animations'
Step 3:
@NgModule({
     imports: [
       BrowserAnimationsModule
     ]
 })

**Comment by devyumao** [comment]
Now 4.0 is supported!
