### ISSUE TITLE
Version 1.0.3+ totally broken in Angular 4 app

### ISSUE THREAD

**Issue by Sky4CE** [devyumao/angular2-busy#46]
Please fix

![image](https://cloud.githubusercontent.com/assets/9821633/24706037/ff07dc4e-1a16-11e7-9366-302fd875ca6b.png)

Should I say that BrowserModule declared only once in app.module? obviously. 
angular2-busy was declared in shared module, so it can be used in any. Everything was perfect on v1.0.2

**Comment by devyumao** [comment]
The latest version is 2.0.1. You may try to update it. 
```shell
npm install --save angular2-busy@latest
```

**Comment by vjangari** [comment]
I am using busy module in shared module and getting same error. (BrowserModule has been already loaded). I am using angular 4.0.1 and angular2-busy latest version

**Comment by vjangari** [comment]
It seems we have issue with Lazy loaded modules. I have 2 lazy loaded modules and each module required this busy module. I am getting error BrowserModule has been already loaded when I load lazy module.

BrowserAnimationsModule internally importing Browser module.

class BrowserAnimationsModule {
}

@NgModule({
  imports: [BrowserModule],
  providers: BROWSER_ANIMATIONS_PROVIDERS,
})

**Comment by vjangari** [comment]
I guess i found solution.
We should import BrowserAnimationsModule  at root module ( AppModule) and busy module should not import BrowserAnimationModule as it is imported in Root module

**Comment by devyumao** [comment]
Thanks, @vjangari , you are right! The bug has been fixed on v2.0.2.

**Comment by Sky4CE** [comment]
@devyumao thanks for fix, have you pushed it to npm?

**Comment by vjangari** [comment]
You are welcome. You may need to update read me file to include browser animation module in root module

**Comment by devyumao** [comment]
@Sky4CE Yes! NPM has the latest version 2.0.3.
