### ISSUE TITLE
Error: Runtime compiler is not loaded

### ISSUE THREAD

**Issue by dangviettuan** [devyumao/angular2-busy#50]
Got "Error: Runtime compiler is not loaded" in component using angular2-busy in ng build -prod

**Comment by samupl** [comment]
I got the same issue - it looks like building without aot seems to make angular2-busy work again, but obviously - without the benefits AOT gives.

**Comment by nourBerro** [comment]
I got the same issue, ng2busy uses compiler to compile the template.
build without aot makes it work but we need a solution for the main issue.
