### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by vvvttt** [devyumao/angular2-busy#6]
Hello,

Thanks for your post.

I am getting the following errors
GET http://localhost:1065/angular2-busy 404 (Not Found)
(index):25 Error: Error: XHR error (404 Not Found) loading http://localhost:1065/angular2-busy(…)
Is this c0mpatible with rc7?
Thanks for your help!

**Comment by devyumao** [comment]
Angular 2.0.0 final is supported now, and you may install Angular 2 Busy by specifying the version:

``` shell
npm install --save angular2-busy@1.0.0
```

**Comment by id717890** [comment]
Hi. Someone help me, please. 
I don`t understand, why I get the messages (in angular 2)!!!

![scr](https://cloud.githubusercontent.com/assets/14906223/19279983/3012f1f6-8ffd-11e6-9703-0c530e7c04aa.png)

**Comment by vvvttt** [comment]
Hello id717890,

Make sure you update your systemjs.config.js file with the correct path, like I did. The error says that its not able to find the component because of the path missing.

![image](https://cloud.githubusercontent.com/assets/22157158/19280691/d4a35f6a-8f9b-11e6-9bd9-4f2e1239374e.png)

**Comment by id717890** [comment]
Hi vvvttt.
Thank you very much for fast answer. Now it is working, ty

**Comment by devyumao** [comment]
Thanks, @vvvttt !
The README has been updated.
