### ISSUE TITLE
Can't bind to 'ngBusy' since it isn't a known property of 'div'

### ISSUE THREAD

**Issue by rajndev** [devyumao/angular2-busy#74]
I'm getting that error with the following line placed in my template:

`<div [ngBusy]="busy"></div>`

`error: Can't bind to 'ngBusy' since it isn't a known property of 'div'`

I have imported the busy module in app.module.ts and have followed the directions in the readme file to the tee. How can I make the directive be recognized?

Thanks.

**Comment by hohler** [comment]
What was your solution?
