### ISSUE TITLE
<div [ERROR ->][ngBusy]="busy"></div>

### ISSUE THREAD

**Issue by calvinKG** [devyumao/angular2-busy#9]
Hi, 

My Project those not start when I add ngBusy directive to my template. 
`<div [ngBusy]="busy"></div>`

![Uploading Capture.PNG…]()

` busy: Subscription;
ngOnInit()
    {

```
    this.busy =  this.dataService.getSystems().subscribe((ut:UserTypes[]) =>{
        this.userType = ut;
    }, error => {
        this.notificationService.printErrorMessage('Failed to load user types. ' + error)
    })
}
```

`

**Comment by php-dev2** [comment]
Getting same error. What to do? Please help.

**Comment by calvinKG** [comment]
@devyumao , please assist with this issue.

**Comment by devyumao** [comment]
Hi calvinKG,
Your `ngOnInit` code has nothing wrong. I guess the error is due to the absence of the `ngBusy` directive. Could you please check if you have correctly imported `BusyModule` in your app module? Or any other error information you could provide? Thank you.

**Comment by calvinKG** [comment]
@devyumao I do have BusyModule in my app module. 

Also when I use this directive it breaks my main.js and my application those not compile correctly. 

error: 404 app/main.js

**Comment by devyumao** [comment]
@calvinKG Could you please show me your `systemjs.config.js`?

This is the config in my file:

``` javascript
{
    paths: {
        'npm:': 'node_modules/'
    },
    map: {
        app: 'app',
        // ...
        'core-js': 'npm:core-js',
        'ts-metadata-helper': 'npm:ts-metadata-helper',
        'angular2-dynamic-component': 'npm:angular2-dynamic-component',
        'angular2-busy': 'npm:angular2-busy'
    },
    packages: {
        app: {
            main: './main.js',
            defaultExtension: 'js'
        },
        // ...
        'core-js': {
            defaultExtension: 'js'
        },
        'ts-metadata-helper': {
            defaultExtension: 'js'
        },
        'angular2-dynamic-component': {
            defaultExtension: 'js'
        },
        'angular2-busy': {
            main: './index.js',
            defaultExtension: 'js'
        }
    }
}
```

**Comment by calvinKG** [comment]
var map = {
        'dist':                        'dist', // 'dist',
        '@angular':                   'node_modules/@angular',
        'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
        'rxjs':                       'node_modules/rxjs',
        'primeng':                    'node_modules/primeng',
        'angular2-busy':               'node_modules/angular2-busy',
        'ng2-bootstrap':              'node_modules/ng2-bootstrap',
        'moment':                     'node_modules/moment/moment.js',
        'angular2-cookie':            'node_modules/angular2-cookie',
        'ng2-file-upload':            'node_modules/ng2-file-upload',
        '@angular/http/testing':      'node_modules/@angular/http/bundles/http-testing.umd.js'

```
};
// packages tells the System loader how to load when no filename and/or no extension
var packages = {
    'dist':                        { main: 'main.js',  defaultExtension: 'js' },
    'rxjs':                        { main: 'Rx.js', defaultExtension: 'js' },
    'angular2-in-memory-web-api':  { main: 'index.js', defaultExtension: 'js' },
    'angular2-cookie':             { main: 'core.js', defaultExtension: 'js' },
    'primeng':                     { defaultExtension: 'js' },
    'angular2-busy':               { main: 'index.js', defaultExtension: 'js' },
    'ng2-bootstrap':               { main: 'ng2-bootstrap.js', defaultExtension: 'js' },
    'ng2-file-upload':             { main: 'ng2-file-upload.js', defaultExtension: 'js' }
};
```

**Comment by calvinKG** [comment]
@devyumao , I see you have added systemJS configuration. Will implement then gibe feedback

**Comment by calvinKG** [comment]
Same error 

![image](https://cloud.githubusercontent.com/assets/1926014/19320236/b6584e2e-90b0-11e6-936e-ae6c79734afc.png)

SystemJS 

` var map = {
        'dist':                        'dist', // 'dist',
        '@angular':                   'node_modules/@angular',
        'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
        'rxjs':                       'node_modules/rxjs',
        'primeng':                    'node_modules/primeng',

```
    'ng2-bootstrap':              'node_modules/ng2-bootstrap',
    'moment':                     'node_modules/moment/moment.js',
    'angular2-cookie':            'node_modules/angular2-cookie',
    'ng2-file-upload':            'node_modules/ng2-file-upload',
    '@angular/http/testing':      'node_modules/@angular/http/bundles/http-testing.umd.js',
    'ts-metadata-helper':         'node_modules/ts-metadata-helper',
    'angular2-dynamic-component': 'node_modules/angular2-dynamic-component',
    'angular2-busy':              'node_modules/angular2-busy'


};
// packages tells the System loader how to load when no filename and/or no extension
var packages = {
    'dist':                        { main: 'main.js',  defaultExtension: 'js' },
    'rxjs':                        { main: 'Rx.js', defaultExtension: 'js' },
    'angular2-in-memory-web-api':  { main: 'index.js', defaultExtension: 'js' },
    'angular2-cookie':             { main: 'core.js', defaultExtension: 'js' },
    'primeng':                     { defaultExtension: 'js' },
    'ng2-bootstrap':               { main: 'ng2-bootstrap.js', defaultExtension: 'js' },
    'ng2-file-upload':             { main: 'ng2-file-upload.js', defaultExtension: 'js' },
    'ts-metadata-helper':          {defaultExtension: 'js'},
    'angular2-dynamic-component':  {defaultExtension: 'js'},
    'angular2-busy':               {main: './index.js', defaultExtension: 'js'}
};`
```

**Comment by calvinKG** [comment]
am also getting this error regarding main.js 

Was able to resolve this issue by uninstalling angular2-busy

![image](https://cloud.githubusercontent.com/assets/1926014/19320336/1cb8e354-90b1-11e6-9efe-90a7f4c1917a.png)

![image](https://cloud.githubusercontent.com/assets/1926014/19320346/30ca20c4-90b1-11e6-8f04-8cfc5862a26d.png)

**Comment by calvinKG** [comment]
after compiling it add  angular2-busy node-module folder  into dist folder.

![image](https://cloud.githubusercontent.com/assets/1926014/19320486/d0bf929e-90b1-11e6-8e59-8b14cc18d359.png)

**Comment by id717890** [comment]
Did somebody solved the problem?
![20161012](https://cloud.githubusercontent.com/assets/14906223/19323079/ed908a40-90d4-11e6-86e8-24570760bac9.png)

**Comment by id717890** [comment]
@devyumao, please tell me, Is it possible to hide buttons on the form until [ngBusy] is loading?

**Comment by KarlPurk** [comment]
I also ran into this problem.  I've managed to get this working by importing `BusyModule` in the feature modules that need it, rather than in `AppModule`.  

This will mean that I'll be importing `BusyModule` multiple times, in different feature modules.  I'm not sure if this will result in any negative consequences though.

**Comment by calvinKG** [comment]
@KarlPurk , am still getting the error.

**Comment by KarlPurk** [comment]
@calvinKG not sure what else to suggest without more information.  Are you sure the angular2-busy dependency is being bundled/loaded correctly?  My next guess would be that SystemJS isn't configured correctly.

**Comment by calvinKG** [comment]
My SystemJS Configuration 

![image](https://cloud.githubusercontent.com/assets/1926014/19806182/6b46d822-9d19-11e6-948a-8e47b2c4b560.png)

**Comment by experimenti** [comment]
The default instructions for webpack (Angular Class Demo) still result in the above error.  I attempted the import at the module and component levels.

**Comment by gvr4wd** [comment]
@calvinKG I ran into the same problem. Make sure the module that uses it in the feature module, if you have feature module, not at the app module. Point it to the right place in SystemJS or Webpack. It looks like your angular2-busy is in dist folder, not node_modules folder.

**Comment by asaisra1** [comment]
I had the same problem . Importing the BusyModule into app's root module did not work . So , try once by including BusyModule directly in imports of the component where you are using ngBusy. This solved the problem.

**Comment by fred-ramage** [comment]
Hello,
 I still have the problem. I'm stuck for now...
 I've imported the module in my component (not in app.component.ts) as requested:

 `import { BusyModule, BusyDirective }                     from 'angular2-busy';`

But I still have the same error: 

> Can't bind to 'ngBusy' since it isn't a known property of 'div'. ("<div [ERROR ->][ngBusy]="busy">


Is there anybody that help ?
As I see, there is a bunch of time no one is heading on for this bug.

Is the project stopped ?

thank you.

**Comment by ccpony** [comment]
This project appears to be abandoned.

**Comment by ccpony** [comment]
I think that dinusuresh's suggestion here: 

https://github.com/devyumao/angular2-busy/issues/33

solved "can't bind..." problem for me.

**Comment by ankit0606** [comment]
Facing the same issue.

**Comment by honginstarbucks** [comment]
still has this problem with angular CLI

I added this in my cli.json 

```
"scripts": [
        "../node_modules/angular2-busy/index.ts"
      ]
```

In vendoer.bundle.js, I can even see `BusyDirective`, doesn't work.
 
any other idea?

**Comment by YaoHuangMark** [comment]
@gvr4wd  yes , you are right !
